# Generated by Django 4.1 on 2023-03-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='job_name',
            new_name='name',
        ),
    ]
